"""Trabalhando_com_arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-sN-tWRQPXzzVyDpN5beFVtmRAvTAdR

#    **Arrays vs Lista**

*   **Exemplo:** Escalar
"""

l1 = [1, 5, 6]
l2 = [3, 7, 6]

l3 = [a + b for a, b in zip(l1, l2)]
print(l3)

"""

*   **Exemplo:** Vetorial

"""

import numpy as np

a1 = np.array(l1)
a2 = np.array(l2)

a3 = a1 + a2
print(a3)

"""#**Arrays 1D: vetores**

*   **Criação de Array**
"""

a1 = np.array([2, 4, 6, 8])
print(a1)

a1 = np.arange(0, 10, 2)
print(a1)

a1 = np.zeros(10)
print(a1)

a1 = 10 * np.ones(10)
print(a1)

"""

*   **Manipulação de Arrays**

"""

a1 = np.array([2, 4, 6, 8])
print(a1)

a1[0]

a1[0:2]

a1[a1 > 4]

"""

*   ***Atributos***


"""

a1.ndim

a1.shape

a1.size

a1.dtype

"""

*   **Métodos **


"""

a1.sort()
print(a1)

a1.tolist()

"""#   **Arrays 2D: Matrizes**

*   **Criação de Matriz**
"""

m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(m1)

"""

*   **Manipulação de Matriz**


"""

m1[1, 2]

m1[:, 2]

m1[1, :]

"""

*   **Atributos**


"""

m1.ndim

m1.shape

m1.size

m1.dtype

"""

*   **Métodos**


"""

m1.sort()
print(m1)

m1.tolist()